In [65]:
import numpy as np
from pyspark.mllib.random import RandomRDDs
from pyspark.mllib.clustering import KMeans, KMeansModel

In [66]:
c1_v = RandomRDDs.normalVectorRDD(sc, 20, 2,numPartitions=2, seed=1).map(lambda v:np.add([1,5],v))

In [67]:
c1_v.stats()

(count: 20, mean: [0.99904353 5.17086964], stdev: [1.09266486 1.17928067], max: [2.84457407 7.55092046], min: [-1.33872715  3.4329441 ])

In [68]:
c2_v = RandomRDDs.normalVectorRDD(sc, 20, 2,numPartitions=2, seed=1).map(lambda v:np.add([5,1],v))

In [69]:
c2_v.stats()

(count: 20, mean: [4.99904353 1.17086964], stdev: [1.09266486 1.17928067], max: [6.84457407 3.55092046], min: [ 2.66127285 -0.5670559 ])

In [70]:
c3_v = RandomRDDs.normalVectorRDD(sc, 20, 2,numPartitions=2, seed=1).map(lambda v:np.add([4,6],v))

In [71]:
c12 = c1_v.union(c2_v)

In [72]:
mydata = c12.union(c3_v)

### K = 1

In [73]:
my_kmModel = KMeans.train(mydata, k=1,maxIterations=10, runs=1,initializationMode='k-means||')

In [74]:
my_kmModel.computeCost(mydata)

608.4104961116808

In [53]:
my_kmModel.clusterCenters

[array([3.33237686, 4.17086964])]

In [58]:
my_kmModel = KMeans.train(mydata, k=3,maxIterations=10, runs=1,initializationMode='k-means||')

In [59]:
my_kmModel.computeCost(mydata)

143.863702609487

In [60]:
my_kmModel.clusterCenters

[array([4.99904353, 1.17086964]),
 array([1.14960082, 5.18709726]),
 array([4.32476012, 6.32538522])]

In [61]:
mydata.stats()

(count: 60, mean: [3.33237686 4.17086964], stdev: [2.0205953 2.4611724], max: [6.84457407 8.55092046], min: [-1.33872715 -0.5670559 ])

In [62]:
my_kmModel = KMeans.train(mydata, k=4,maxIterations=10, runs=1,initializationMode='k-means||')

In [63]:
my_kmModel.computeCost(mydata)

121.58377271347561

In [64]:
my_kmModel.clusterCenters

[array([1.14960082, 5.18709726]),
 array([4.9731138 , 1.04560381]),
 array([3.91907497, 7.24188798]),
 array([4.86010619, 5.1006086 ])]